apiVersion: v1
kind: Service
metadata:
  name: chaos-ui
  labels:
    app.kubernetes.io/name: chaos-ui
    app.kubernetes.io/part-of: heliantheon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chaos-ui
  ports:
    - name: http
      port: 8080
      targetPort: http
