apiVersion: v1
kind: Service
metadata:
  name: atlas-hermes
  labels:
    app.kubernetes.io/name: atlas-hermes
    app.kubernetes.io/part-of: heliantheon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: atlas-hermes
  ports:
    - name: http
      port: 8080
      targetPort: http

