apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chaos-ui
  labels:
    app.kubernetes.io/name: chaos-ui
    app.kubernetes.io/part-of: heliantheon
spec:
  ingressClassName: traefik
  rules:
    - host: chaos.heliannuuthus.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chaos-ui
                port:
                  name: http
